research_candidates_task:
  description: >
    Conduct through research to find potential candidates for the specified job.
    Utilize various online resources and databases to gather a comprehensive list of potential candidates.
    Ensure that the candidates meet the job requirements provided.

    Job Requirements:
    {job_requirements}
  expected_output: >
    A list of 10 potential candidates with their contact information and brief profiles highlighting their suitability.
  agent: researcher

reporting_task:
  description: >
    Analyze the profiles of the candidates collected and rank them based on the job requirements.
    Provide a summary of strengths and weaknesses for each candidate.
  expected_output: >
    A ranked list of candidates with a brief evaluation summary for each.
  agent: reporting_analyst
